### PR TITLE
More detailed failure message for host check

### PR DESCRIPTION
**Pull request by byzek**
Needed to distinguish between "didn't provide hostname" and "hostname lookup failed"

### CODE REVIEW

**Review by sbezverk — COMMENTED** [review]
Any chance you can add unit tests to test all possible combinations?

**Comment by byzek** [comment]
Yeah, will get around to it...

**Comment by sbezverk** [comment]
You can use this code and extend it with other cases which needs to be tested

```
func TestHostAddrValidator(t *testing.T) {
        tests := []struct {
                name  string
                input string
                fail  bool
        }{
                {
                        name:  "valid ipv4 and port",
                        input: "1.1.1.1:8080",
                        fail:  false,
                },
                {
                        name:  "valid ipv4 and mo port",
                        input: "1.1.1.1",
                        fail:  true,
                },
                {
                        name:  "valid dns and port",
                        input: "localhost:8080",
                        fail:  false,
                },
                {
                        name:  "valid dns and no port",
                        input: "localhost",
                        fail:  true,
                },
        }
        for _, tt := range tests {
                t.Run(tt.name, func(t *testing.T) {
                        err := HostAddrValidator(tt.input)
                        if err != nil && !tt.fail {
                                t.Fatalf("supposed to succeed but fail with errorL %+v", err)
                        }
                        if err == nil && tt.fail {
                                t.Fatalf("supposed to fail but succeeded")
                        }
                })
        }
}
```

Serguei
From: Jeff Byzek ***@***.***>
Reply-To: sbezverk/tools ***@***.***>
Date: Wednesday, August 24, 2022 at 5:09 PM
To: sbezverk/tools ***@***.***>
Cc: sbezverk ***@***.***>, Comment ***@***.***>
Subject: Re: [sbezverk/tools] More detailed failure message for host check (PR #1)


Yeah, will get around to it...

**Comment by byzek** [comment]
Ok, added tests and cleaned up the URL validation, too.

**Review by sbezverk — APPROVED** [review]
Thank you for PR

**Pull request merged**
